### ISSUE TITLE
Enhancement: Release Pubspec Class as an own package

### ISSUE THREAD

**Issue by jxstxn1** [dart-lang/pubspec_parse#121]
It would be great to have an actively maintained Pubspec Data Class.
The current [pubspec package](https://pub.dev/packages/pubspec) seems unmaintained and is missing quite a lot of properties

**Comment by kevmoo** [comment]
What's wrong with https://pub.dev/documentation/pubspec_parse/latest/pubspec_parse/Pubspec-class.html ?

**Comment by jxstxn1** [comment]
Nothing😅
I must have totally overlooked this one while I was doing my research.

It's just that quite a few popular Packages rely on this one, but nothing the dart team could change.

**Comment by kevmoo** [comment]
Well, you could ask the author to discontinue the package and point to `pubspec_parse` as an option.
