### ISSUE TITLE
forbid undefined properties

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pubspec_parse#34]
Currently, `pubspec_parse` will accept a pubspec that contains undefined properties. That is properties not specified to have any meaning in a `pubspec.yaml` file. These properties are just ignored.

I propose that we forbid presence of such properties, to ensure forward compatibility, as we might be adding new properties in the future.

**Comment by jonasfj** [comment]
That [current documentation](https://github.com/dart-lang/site-www/blob/4f5aafede80bc2858efbc42d56a11712ad881ecb/src/tools/pub/pubspec.md#supported-fields) for `pubspec.yaml` says:
> Pub ignores all other fields.

So this would definitely be a breaking change. But it's probably something we could do.

**Comment by kwalrath** [comment]
I have a vague memory of some frameworks adding fields to the pubspec. But maybe these were just fields that were officially added later.

**Comment by munificent** [comment]
This is working as intended. *Ignoring* additional fields is how we ensure backwards compatibility. It allows older versions of pubspec_parse (and pub in general) to parse newer pubspecs that may have fields that were added and used by later versions.

There is some risk that we might want to add a new field that some others are already using. But, in practice, that hasn't been much of a concern, and the backwards compatibility is a real benefit. Also, some third party tools use their own fields in the pubspec. We want people to do this judiciously so collisions don't happen, but when done with care, it works well and minimizes the number of manifest files cluttering up the top level of a user's package directory.

**Comment by jonasfj** [comment]
Backwards compatibility is a good point. However, if the new properties being used have semantic importance, then failure to support them might be a breaking change. I guess this is then enforced by specifying the sdk version.

note, @isoos compiled a list of a properties used in pubspecs published on pub:
https://github.com/dart-lang/pub-dartlang-dart/issues/1898#issuecomment-450872744

It's clear that people are mistyping `authors`, `dev_dependency_overrides`, `dev-dependencies`, `dev_dependency`, and `dependecies` in published package specs...

------
The use of properties could be linked to the `sdk` version. That way you can only use a field if you are not backwards compatible with older versions.

----
I'm okay with leaving this as is. I agree we generally don't have huge problems. We should probably remove un-interpreted fields when packages are published to ensure forward compatibility of the package repository we have in storage on `pub.dartlang.org`.

**Comment by pq** [comment]
> It's clear that people are mistyping authors, dev_dependency_overrides, dev-dependencies, dev_dependency, and dependecies in published package specs...

@jonasfj: one thought would be a lint rule that flags unsupported properties?  (Any context-specific ones could be individually ignored.)

**Comment by pq** [comment]
https://github.com/dart-lang/linter/issues/1339 to track.

**Comment by isoos** [comment]
A different take on the same core issue: https://github.com/dart-lang/pubspec_parse/issues/35
