### ISSUE TITLE
best-effort parsing (without throwing exceptions)

### ISSUE THREAD

**Issue by isoos** [dart-lang/pubspec_parse#35]
When the pub site reads previously uploaded `pubspec.yaml` files, we need to be lenient on the content. An property that may be restricted to a specific format now could be present in an uploaded file, and we should be able to process it without throwing exceptions on the site.

The particular example is the `repository` key of an old package: https://github.com/dart-lang/pub-dartlang-dart/issues/1898#issuecomment-450808424 

However, I can imagine format changes or other restrictions that would make an old `pubspec.yaml` invalid in the current strict parsing. Instead of hard failures, we'd like to have best-effort parsing that won't throw exceptions on bad input. Such bad input could be:
- type mismatch (`String` vs `{}`)
- format mismatch (`String` vs `Uri`)
- required vs. optional...

Could this be supported by `pubspec_parse`?

**Comment by jonasfj** [comment]
If we take this approach, then:

 * Isn't this also the kind of pubspec parser that `pub` will need to use when reading existing packages?
 * It's really only for reading the users pubspec and for uploading packages that we want parsing stronger than best-effort.

**Comment by isoos** [comment]
I think strict parsing has benefits in:
- `pub publish` (and pub site's upload validation)
- `pana` (because it tries to measure packages to be every-green), although `pana` could be fine with both.

Meanwhile, best-effort parsing is needed for every other access on pub site (to not break on old values).

**Comment by kevmoo** [comment]
~crazy idea: we could introduce a throw-or-log function for these types of
checks – back it with a Zone variable so you can call the root parse
function with a 'logIssuesInsteadOfThrow' handler – or something like that

**Comment by isoos** [comment]
@kevmoo: is the zone required because of the call chain of parsing embedded classes? (`A.fromJson` calling `B.fromJson` calling `C.fromJson`?) Would it be on the similar level of complexity to have a flag on `JsonSerializable` that generates the `fromJson` with a simpler callback?

**Comment by kevmoo** [comment]
That'd be a whole new feature in `json_serializable` – seems a bit complex. We could consider it, though...

**Comment by jonasfj** [comment]
Let's not modify `json_serializable`, we can just parse each top-level property with `fromJson` on the property.
