### ISSUE TITLE
Add support for parsing topics

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pubspec_parse#92]
Remember that when parsing in lenient mode, we must ignore errors when `topics` is malformed. Otherwise, we might break existing packages.

**Comment by devoncarew** [comment]
Is this something we want to take on soon? I believe the work to add topics to pub is now complete.

**Comment by kevmoo** [comment]
Fixed in 09fa72eb6755c108e69a55d0a82f6251cdf4479a
